// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NPI.Data.Context;

#nullable disable

namespace NPI.Data.Migrations
{
    [DbContext(typeof(NpiDbContext))]
    [Migration("20260212064440_usertablesadded")]
    partial class usertablesadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("NPI.Data.Entities.ChangeLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldChanged")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("NpiRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NpiRecordId", "ChangedDate");

                    b.ToTable("ChangeLogEntries");
                });

            modelBuilder.Entity("NPI.Data.Entities.FormulaSpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Batches")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Blender")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Density")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("FormulaName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FormulaSize")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("KG")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<int>("NpiRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OrderQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("PkgType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdType")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServPerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalServings")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalUnits")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NpiRecordId")
                        .IsUnique();

                    b.ToTable("FormulaSpecs");
                });

            modelBuilder.Entity("NPI.Data.Entities.LaborItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ChangeOver")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CostPerEach")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Head")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOverhead")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Machine")
                        .HasColumnType("TEXT");

                    b.Property<int>("NpiRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Run")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UnitsPerHour")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NpiRecordId");

                    b.ToTable("LaborItems");
                });

            modelBuilder.Entity("NPI.Data.Entities.NpiDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NpiRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UploadedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NpiRecordId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("NPI.Data.Entities.NpiNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("NpiRecordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NpiRecordId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("NPI.Data.Entities.NpiRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BulkCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FGCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FormulaSize")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemDescription")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OrderQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("POValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PackageType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackoutDescription")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuoteNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SalesRep1")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SalesRep2")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Servings")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StdQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalUnits")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemCode");

                    b.HasIndex("QuoteNumber");

                    b.HasIndex("Status");

                    b.ToTable("NpiRecords");
                });

            modelBuilder.Entity("NPI.Data.Entities.PackagingComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCustomerSupplied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("NpiRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NpiRecordId");

                    b.ToTable("PackagingComponents");
                });

            modelBuilder.Entity("NPI.Data.Entities.PackagingOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NpiRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NpiRecordId");

                    b.ToTable("PackagingOptions");
                });

            modelBuilder.Entity("NPI.Data.Entities.PilotRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnsweredBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AnsweredDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("NpiRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NpiRecordId");

                    b.ToTable("PilotRequirements");
                });

            modelBuilder.Entity("NPI.Data.Entities.PlannerQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnsweredBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AnsweredDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NpiRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NpiRecordId");

                    b.ToTable("PlannerQuestions");
                });

            modelBuilder.Entity("NPI.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "NPIManager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Planner"
                        },
                        new
                        {
                            Id = 4,
                            Name = "QualityOfficer"
                        },
                        new
                        {
                            Id = 5,
                            Name = "PackagingExec"
                        });
                });

            modelBuilder.Entity("NPI.Data.Entities.SetupQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnsweredBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AnsweredDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("NpiRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NpiRecordId");

                    b.ToTable("SetupQuestions");
                });

            modelBuilder.Entity("NPI.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "superadmin@ans.com",
                            Password = "123456",
                            UserName = "superadmin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "npi.manager@ans.com",
                            Password = "123456",
                            UserName = "npimanager"
                        },
                        new
                        {
                            Id = 3,
                            Email = "planner@ans.com",
                            Password = "123456",
                            UserName = "planner"
                        },
                        new
                        {
                            Id = 4,
                            Email = "quality@ans.com",
                            Password = "123456",
                            UserName = "quality"
                        },
                        new
                        {
                            Id = 5,
                            Email = "packaging@ans.com",
                            Password = "123456",
                            UserName = "packaging"
                        });
                });

            modelBuilder.Entity("NPI.Data.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            RoleId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            RoleId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            RoleId = 5,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("NPI.Data.Entities.ChangeLogEntry", b =>
                {
                    b.HasOne("NPI.Data.Entities.NpiRecord", "NpiRecord")
                        .WithMany("ChangeLog")
                        .HasForeignKey("NpiRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpiRecord");
                });

            modelBuilder.Entity("NPI.Data.Entities.FormulaSpec", b =>
                {
                    b.HasOne("NPI.Data.Entities.NpiRecord", "NpiRecord")
                        .WithOne("FormulaSpec")
                        .HasForeignKey("NPI.Data.Entities.FormulaSpec", "NpiRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpiRecord");
                });

            modelBuilder.Entity("NPI.Data.Entities.LaborItem", b =>
                {
                    b.HasOne("NPI.Data.Entities.NpiRecord", "NpiRecord")
                        .WithMany("LaborItems")
                        .HasForeignKey("NpiRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpiRecord");
                });

            modelBuilder.Entity("NPI.Data.Entities.NpiDocument", b =>
                {
                    b.HasOne("NPI.Data.Entities.NpiRecord", "NpiRecord")
                        .WithMany("Documents")
                        .HasForeignKey("NpiRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpiRecord");
                });

            modelBuilder.Entity("NPI.Data.Entities.NpiNote", b =>
                {
                    b.HasOne("NPI.Data.Entities.NpiRecord", "NpiRecord")
                        .WithMany("Notes")
                        .HasForeignKey("NpiRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpiRecord");
                });

            modelBuilder.Entity("NPI.Data.Entities.PackagingComponent", b =>
                {
                    b.HasOne("NPI.Data.Entities.NpiRecord", "NpiRecord")
                        .WithMany("PackagingComponents")
                        .HasForeignKey("NpiRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpiRecord");
                });

            modelBuilder.Entity("NPI.Data.Entities.PackagingOption", b =>
                {
                    b.HasOne("NPI.Data.Entities.NpiRecord", "NpiRecord")
                        .WithMany("PackagingOptions")
                        .HasForeignKey("NpiRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpiRecord");
                });

            modelBuilder.Entity("NPI.Data.Entities.PilotRequirement", b =>
                {
                    b.HasOne("NPI.Data.Entities.NpiRecord", "NpiRecord")
                        .WithMany("PilotRequirements")
                        .HasForeignKey("NpiRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpiRecord");
                });

            modelBuilder.Entity("NPI.Data.Entities.PlannerQuestion", b =>
                {
                    b.HasOne("NPI.Data.Entities.NpiRecord", "NpiRecord")
                        .WithMany("PlannerQuestions")
                        .HasForeignKey("NpiRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpiRecord");
                });

            modelBuilder.Entity("NPI.Data.Entities.SetupQuestion", b =>
                {
                    b.HasOne("NPI.Data.Entities.NpiRecord", "NpiRecord")
                        .WithMany("SetupQuestions")
                        .HasForeignKey("NpiRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpiRecord");
                });

            modelBuilder.Entity("NPI.Data.Entities.UserRole", b =>
                {
                    b.HasOne("NPI.Data.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPI.Data.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NPI.Data.Entities.NpiRecord", b =>
                {
                    b.Navigation("ChangeLog");

                    b.Navigation("Documents");

                    b.Navigation("FormulaSpec");

                    b.Navigation("LaborItems");

                    b.Navigation("Notes");

                    b.Navigation("PackagingComponents");

                    b.Navigation("PackagingOptions");

                    b.Navigation("PilotRequirements");

                    b.Navigation("PlannerQuestions");

                    b.Navigation("SetupQuestions");
                });

            modelBuilder.Entity("NPI.Data.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("NPI.Data.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
